const buscadorTallerQuery = (placa, distrito, tipo_taller) => {
    
    return `
SELECT 
	DEDUCIBLE.ID AS deducible, 
    DEDUCIBLE.PAGO AS copago, 
    DEDUCIBLE.MONEDA AS moneda,
    TIPO_SUCURSAL.NOMBRE AS tipo,
    VEHICULO.MARCA AS marca,
    TALLER.NOMBRE AS taller
FROM DEDUCIBLE
INNER JOIN COBERTURA ON DEDUCIBLE.ID = COBERTURA.PK_DEDUCUBLE
INNER JOIN POLIZA ON COBERTURA.PK_POLIZA = POLIZA.ID
INNER JOIN VEHICULO ON POLIZA.PK_VEHICULO = VEHICULO.ID
INNER JOIN CLIENTE ON VEHICULO.PK_CLIENTE = CLIENTE.ID
INNER JOIN CLAUSULA ON POLIZA.ID = CLAUSULA.PK_POLIZA
INNER JOIN CLAUSULA_VEHA ON CLAUSULA.ID = CLAUSULA_VEHA.PK_CLAUSULA
INNER JOIN SUCURSAL_VEHA_RED_TALLER ON CLAUSULA_VEHA.ID = SUCURSAL_VEHA_RED_TALLER.PK_SUCURSAL_VEHA
INNER JOIN RED_TALLER ON SUCURSAL_VEHA_RED_TALLER.PK_RED_TALLER = RED_TALLER.ID
INNER JOIN TALLER ON RED_TALLER.ID = TALLER.PK_RED_TALLER
INNER JOIN SUCURSAL ON TALLER.ID = SUCURSAL.PK_TALLER
INNER JOIN TIPO_SUCURSAL ON SUCURSAL.PK_TIPO_SUCURSAL = TIPO_SUCURSAL.ID
WHERE VEHICULO.PLACA = ${VEHICULO} AND CLIENTE.DISTRITO = ${DISTRITO} AND TIPO_SUCURSAL.NOMBRE = ${TIPO_SUCURSAL}`
};

exports.buscadorTallerQuery = buscadorTallerQuery;